### ISSUE TITLE
spectrum viewer partly broken for sda-mods?

### ISSUE THREAD

**Issue by gieses** [Rappsilber-Laboratory/spectrum#46]
@lars-kolbowski probably? 

Spectrumviewer issue:
I think the parsing of SDA mods is not working fully.  In the new  "show settings" (for me its new) menu the mods are not shown correctly.

Example: the mods in the sequence are "sda-loop" and "sda-alk". The described "show settings" window shows the following entries:
sda ~ 110
loop ~ 0
cm ~ 57
alk ~ 0

Data available via search id: 12303, scan: 56247. You have to run the FDR via the webinterface to see this scan since it is not auto validated.

I don't know how far this effects the view etc....

**Comment by lars-kolbowski** [comment]
ah thanks for pointing that out. I fixed the bug already for xiSPEC but not in the integrated version. Basically the mod parser doesn't know that the '-' char is allowed for modifications.
will deploy it in a sec

**Comment by lars-kolbowski** [comment]
should be fixed: https://github.com/Rappsilber-Laboratory/spectrum/commit/dd6ab725fb5d5991c2c9d6bb291c2004be411abc

**Comment by gieses** [comment]
is fixed! thx
